export const CANONICAL_ACHIEVEMENTS = [
  {
    slug: 'first-steps',
    title: 'First Steps',
    description: 'Complete your first lesson on BPFQuest.',
    category: 'FOUNDATIONS',
    icon: '🌱',
    xpReward: 25,
    requirement: 'Complete 1 lesson in any course',
    isHidden: false,
    order: 1,
  },
  {
    slug: 'linux-explorer',
    title: 'Linux Explorer',
    description: 'Complete all modules and lessons in Linux Fundamentals.',
    category: 'FOUNDATIONS',
    icon: '🐧',
    xpReward: 150,
    requirement: 'Complete the entire Linux Fundamentals course',
    isHidden: false,
    order: 2,
  },
  {
    slug: 'mission-accepted',
    title: 'Mission Accepted',
    description: 'Successfully solve and pass your first hands-on challenge.',
    category: 'MISSIONS',
    icon: '🎯',
    xpReward: 50,
    requirement: 'Complete 1 hands-on mission',
    isHidden: false,
    order: 3,
  },
  {
    slug: 'process-sleuth',
    title: 'Process Sleuth',
    description: 'Pinpoint and inspect telemetry processes via /proc.',
    category: 'TRACING',
    icon: '🔍',
    xpReward: 50,
    requirement: 'Complete the "Observe a Process" mission',
    isHidden: false,
    order: 4,
  },
  {
    slug: 'file-investigator',
    title: 'File Descriptor Master',
    description: 'Trace open file streams and discover leaking socket references.',
    category: 'FOUNDATIONS',
    icon: '📂',
    xpReward: 50,
    requirement: 'Complete the "Explore File Descriptors" mission',
    isHidden: false,
    order: 5,
  },
  {
    slug: 'net-navigator',
    title: 'Network Navigator',
    description: 'Inspect dormant link states and detect interface MTU constraints.',
    category: 'NETWORKING',
    icon: '🌐',
    xpReward: 50,
    requirement: 'Complete the "Find a Network Interface" mission',
    isHidden: false,
    order: 6,
  },
  {
    slug: 'tracer',
    title: 'Tracer',
    description: 'Attach probes to sched_process_exec and trace kernel lifecycle events.',
    category: 'TRACING',
    icon: '⚡',
    xpReward: 75,
    requirement: 'Complete the "Trace a Process Event" mission',
    isHidden: false,
    order: 7,
  },
  {
    slug: 'first-bpf-verifier',
    title: 'Verifier Approved',
    description: 'Structure a clean eBPF ELF program with bounded sections and passes verifier inspection.',
    category: 'EBPF',
    icon: '🛡️',
    xpReward: 100,
    requirement: 'Complete the "First eBPF Program" mission or playground exercise',
    isHidden: false,
    order: 8,
  },
];