/**
 * Stage 7: Isolated Lab Execution Infrastructure Types & Enums
 *
 * Defines strictly controlled state lifecycles and error codes across the
 * execution pipeline: API -> Queue -> Worker -> LabProvider -> Sandbox -> Validator.
 */

export const ExecutionJobStatus = {
  REQUESTED: 'REQUESTED',
  QUEUED: 'QUEUED',
  CREATING: 'CREATING',
  READY: 'READY',
  RUNNING: 'RUNNING',
  COLLECTING: 'COLLECTING',
  VALIDATING: 'VALIDATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  TIMEOUT: 'TIMEOUT',
  CANCELLED: 'CANCELLED',
  RESOURCE_LIMIT: 'RESOURCE_LIMIT',
};

export const LabState = {
  CREATING: 'CREATING',
  READY: 'READY',
  RUNNING: 'RUNNING',
  TERMINATED: 'TERMINATED',
  DESTROYED: 'DESTROYED',
  FAILED: 'FAILED',
};

export const ExecutionErrorCode = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  QUEUE_UNAVAILABLE: 'QUEUE_UNAVAILABLE',
  QUEUE_FULL: 'QUEUE_FULL',
  LAB_CREATE_FAILED: 'LAB_CREATE_FAILED',
  LAB_UNAVAILABLE: 'LAB_UNAVAILABLE',
  LAB_EXECUTION_UNAVAILABLE: 'LAB_EXECUTION_UNAVAILABLE',
  EBPF_LAB_UNAVAILABLE: 'EBPF_LAB_UNAVAILABLE',
  EXECUTION_TIMEOUT: 'EXECUTION_TIMEOUT',
  RESOURCE_LIMIT: 'RESOURCE_LIMIT',
  OUTPUT_LIMIT: 'OUTPUT_LIMIT',
  OUTPUT_LIMIT_EXCEEDED: 'OUTPUT_LIMIT_EXCEEDED',
  COMPILATION_FAILED: 'COMPILATION_FAILED',
  EXECUTION_FAILED: 'EXECUTION_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  USER_CANCELLED: 'USER_CANCELLED',
  INFRASTRUCTURE_ERROR: 'INFRASTRUCTURE_ERROR',
};

export const LabProviderType = {
  MOCK: 'mock',
  CONTAINER: 'container',
  FIRECRACKER: 'firecracker',
};